//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaWinUI.ColorPicker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaWinUI.ColorPicker.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        internal static string ContentHSVComboBoxItem {
            get {
                return ResourceManager.GetString("ContentHSVComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        internal static string ContentRGBComboBoxItem {
            get {
                return ResourceManager.GetString("ContentRGBComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D navigation with arrow keys.
        /// </summary>
        internal static string HelpTextColorSpectrum {
            get {
                return ResourceManager.GetString("HelpTextColorSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke to show or hide the text entry fields..
        /// </summary>
        internal static string HelpTextMoreButton {
            get {
                return ResourceManager.GetString("HelpTextMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D slider.
        /// </summary>
        internal static string LocalizedControlTypeColorSpectrum {
            get {
                return ResourceManager.GetString("LocalizedControlTypeColorSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string TextAlphaLabel {
            get {
                return ResourceManager.GetString("TextAlphaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string TextBlueLabel {
            get {
                return ResourceManager.GetString("TextBlueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string TextGreenLabel {
            get {
                return ResourceManager.GetString("TextGreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string TextHueLabel {
            get {
                return ResourceManager.GetString("TextHueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string TextMoreButtonLabelCollapsed {
            get {
                return ResourceManager.GetString("TextMoreButtonLabelCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        internal static string TextMoreButtonLabelExpanded {
            get {
                return ResourceManager.GetString("TextMoreButtonLabelExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string TextRedLabel {
            get {
                return ResourceManager.GetString("TextRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string TextSaturationLabel {
            get {
                return ResourceManager.GetString("TextSaturationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string TextValueLabel {
            get {
                return ResourceManager.GetString("TextValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% opacity.
        /// </summary>
        internal static string ToolTipStringAlphaSlider {
            get {
                return ResourceManager.GetString("ToolTipStringAlphaSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue {0} ({1}).
        /// </summary>
        internal static string ToolTipStringHueSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringHueSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue {0}.
        /// </summary>
        internal static string ToolTipStringHueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringHueSliderWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation {0} ({1}).
        /// </summary>
        internal static string ToolTipStringSaturationSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringSaturationSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation {0}.
        /// </summary>
        internal static string ToolTipStringSaturationSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringSaturationSliderWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} ({1}).
        /// </summary>
        internal static string ToolTipStringValueSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringValueSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0}.
        /// </summary>
        internal static string ToolTipStringValueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringValueSliderWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Hue {1}, Saturation {2}, Brightness {3}.
        /// </summary>
        internal static string ValueStringColorSpectrumWithColorName {
            get {
                return ResourceManager.GetString("ValueStringColorSpectrumWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue {0}, Saturation {1}, Brightness {2}.
        /// </summary>
        internal static string ValueStringColorSpectrumWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringColorSpectrumWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string ValueStringHueSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringHueSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}.
        /// </summary>
        internal static string ValueStringHueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringHueSliderWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string ValueStringSaturationSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringSaturationSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}.
        /// </summary>
        internal static string ValueStringSaturationSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringSaturationSliderWithoutColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string ValueStringValueSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringValueSliderWithColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ValueStringValueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringValueSliderWithoutColorName", resourceCulture);
            }
        }
    }
}
